// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: prime_number/prime_number.proto

package primepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Number struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Number) Reset() {
	*x = Number{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_number_prime_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_prime_number_prime_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_prime_number_prime_number_proto_rawDescGZIP(), []int{0}
}

func (x *Number) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PrimeFactor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prime int32 `protobuf:"varint,1,opt,name=prime,proto3" json:"prime,omitempty"`
}

func (x *PrimeFactor) Reset() {
	*x = PrimeFactor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prime_number_prime_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrimeFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeFactor) ProtoMessage() {}

func (x *PrimeFactor) ProtoReflect() protoreflect.Message {
	mi := &file_prime_number_prime_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeFactor.ProtoReflect.Descriptor instead.
func (*PrimeFactor) Descriptor() ([]byte, []int) {
	return file_prime_number_prime_number_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeFactor) GetPrime() int32 {
	if x != nil {
		return x.Prime
	}
	return 0
}

var File_prime_number_prime_number_proto protoreflect.FileDescriptor

var file_prime_number_prime_number_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x20, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x32, 0x42, 0x0a, 0x18, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x09, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73,
	0x65, 0x12, 0x07, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x0c, 0x2e, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prime_number_prime_number_proto_rawDescOnce sync.Once
	file_prime_number_prime_number_proto_rawDescData = file_prime_number_prime_number_proto_rawDesc
)

func file_prime_number_prime_number_proto_rawDescGZIP() []byte {
	file_prime_number_prime_number_proto_rawDescOnce.Do(func() {
		file_prime_number_prime_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_prime_number_prime_number_proto_rawDescData)
	})
	return file_prime_number_prime_number_proto_rawDescData
}

var file_prime_number_prime_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_prime_number_prime_number_proto_goTypes = []interface{}{
	(*Number)(nil),      // 0: Number
	(*PrimeFactor)(nil), // 1: PrimeFactor
}
var file_prime_number_prime_number_proto_depIdxs = []int32{
	0, // 0: PrimeNumberDecomposition.Decompose:input_type -> Number
	1, // 1: PrimeNumberDecomposition.Decompose:output_type -> PrimeFactor
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_prime_number_prime_number_proto_init() }
func file_prime_number_prime_number_proto_init() {
	if File_prime_number_prime_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prime_number_prime_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Number); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prime_number_prime_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrimeFactor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prime_number_prime_number_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prime_number_prime_number_proto_goTypes,
		DependencyIndexes: file_prime_number_prime_number_proto_depIdxs,
		MessageInfos:      file_prime_number_prime_number_proto_msgTypes,
	}.Build()
	File_prime_number_prime_number_proto = out.File
	file_prime_number_prime_number_proto_rawDesc = nil
	file_prime_number_prime_number_proto_goTypes = nil
	file_prime_number_prime_number_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeNumberDecompositionClient is the client API for PrimeNumberDecomposition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberDecompositionClient interface {
	Decompose(ctx context.Context, in *Number, opts ...grpc.CallOption) (PrimeNumberDecomposition_DecomposeClient, error)
}

type primeNumberDecompositionClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeNumberDecompositionClient(cc grpc.ClientConnInterface) PrimeNumberDecompositionClient {
	return &primeNumberDecompositionClient{cc}
}

func (c *primeNumberDecompositionClient) Decompose(ctx context.Context, in *Number, opts ...grpc.CallOption) (PrimeNumberDecomposition_DecomposeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberDecomposition_serviceDesc.Streams[0], "/PrimeNumberDecomposition/Decompose", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberDecompositionDecomposeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberDecomposition_DecomposeClient interface {
	Recv() (*PrimeFactor, error)
	grpc.ClientStream
}

type primeNumberDecompositionDecomposeClient struct {
	grpc.ClientStream
}

func (x *primeNumberDecompositionDecomposeClient) Recv() (*PrimeFactor, error) {
	m := new(PrimeFactor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberDecompositionServer is the server API for PrimeNumberDecomposition service.
type PrimeNumberDecompositionServer interface {
	Decompose(*Number, PrimeNumberDecomposition_DecomposeServer) error
}

// UnimplementedPrimeNumberDecompositionServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberDecompositionServer struct {
}

func (*UnimplementedPrimeNumberDecompositionServer) Decompose(*Number, PrimeNumberDecomposition_DecomposeServer) error {
	return status.Errorf(codes.Unimplemented, "method Decompose not implemented")
}

func RegisterPrimeNumberDecompositionServer(s *grpc.Server, srv PrimeNumberDecompositionServer) {
	s.RegisterService(&_PrimeNumberDecomposition_serviceDesc, srv)
}

func _PrimeNumberDecomposition_Decompose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Number)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberDecompositionServer).Decompose(m, &primeNumberDecompositionDecomposeServer{stream})
}

type PrimeNumberDecomposition_DecomposeServer interface {
	Send(*PrimeFactor) error
	grpc.ServerStream
}

type primeNumberDecompositionDecomposeServer struct {
	grpc.ServerStream
}

func (x *primeNumberDecompositionDecomposeServer) Send(m *PrimeFactor) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberDecomposition_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PrimeNumberDecomposition",
	HandlerType: (*PrimeNumberDecompositionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Decompose",
			Handler:       _PrimeNumberDecomposition_Decompose_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "prime_number/prime_number.proto",
}
